[package]
name = "wasm-lib"
version = "0.1.0"
edition = "2021"
authors = ["glycogen94 <ingeunlee@kookmin.ac.kr>"]
description = "WASM library for the Next.js + Rust monorepo"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.89"
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.39"

[features]
default = ["console_error_panic_hook"]

[profile.release]
opt-level = 3
lto = true
