[package]
name = "zk_circuits"
version = "0.1.0"
edition = "2021"
authors = ["glycogen94 <ingeunlee@kookmin.ac.kr>"]
description = "ZK circuits and WASM bindings for the Verifiable Gacha Game Demo"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"] # cdylib for WASM, rlib for integration tests/scripts

[dependencies]
wasm-bindgen = "0.2.89"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
getrandom = { version = "0.2", features = ["js"] }
web-sys = { version = "0.3", features = ["console"] }
hex = "0.4"
once_cell = "1.19"
thiserror = "1.0"
console_error_panic_hook = { version = "0.1.7", optional = true }
parking_lot = "0.12"

# Arkworks - Focus on disabling defaults only where needed for no_std runtime
ark-ff = { version = "^0.5.0", default-features = false }
ark-ec = { version = "^0.5.0", default-features = false }
ark-bls12-381 = { version = "^0.5.0", default-features = false, features = ["curve"] }
ark-std = { version = "^0.5.0", default-features = false } # Add "parallel" if needed, "print-trace" is not working in WASM because using Instant
ark-relations = { version = "^0.5.0", default-features = false }
ark-r1cs-std = { version = "^0.5.0", default-features = false }
ark-snark = { version = "^0.5.0", default-features = false }
ark-groth16 = { version = "^0.5.0", default-features = false, features = ["r1cs"] }
ark-crypto-primitives = { version = "^0.5.0", default-features = false, features = ["crh", "merkle_tree", "sponge"] }
ark-serialize = { version = "^0.5.0", default-features = false, features = ["derive"] }
[dev-dependencies]
wasm-bindgen-test = "0.3.39"

[features]
default = []
panic_hook = ["console_error_panic_hook"]
# parallel = ["ark-std/parallel", "ark-crypto-primitives/parallel"] # Enable parallel features if needed

[profile.release]
opt-level = 3 # Optimize for speed and size
lto = true      # Link-Time Optimization
codegen-units = 1 # Better optimization potential
panic = 'abort'   # Smaller code size on panic
